---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        user_name: parkerpeater
  lint:
    name: ansible-lint
  playbooks:
    converge: ../resources/playbooks/playbook.yml
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../resources/tests/base
  lint:
    name: flake8
