---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        user_name: parkerpeater
        user_groups: wheel
  lint:
    name: ansible-lint
scenario:
  name: adminuser
verifier:
  name: testinfra
  lint:
    name: flake8
