---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        user_name: parkerpeater
        user_groups: wheel
        user_authorized_key: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCqGKukO1De7zhZj6+H0qtjTkVxwTCpvKe4eCZ0FPqri0cb2JZfXJ/DgYSF6vUpwmJG8wVQZKjeGcjDOL5UlsuusFncCzWBQ7RKNUSesmQRMSGkVb13j+skZ6UtW+5u09lHNsj6tQ51s1SPrCBkedbNf0Tp0GbMJDyR4e9T04ZZwIDAQAB"
  lint:
    name: ansible-lint
  playbooks:
    converge: ../resources/playbooks/playbook.yml
scenario:
  name: adminuser
verifier:
  name: testinfra
  directory: ../resources/tests/base
  additional_files_or_dirs:
    - ../sudos/
  lint:
    name: flake8
